In [1]:
import numpy as np

# Defining lists and numpy arrays

In [3]:
alist = [1,2,3,4,5] # Define a python list. It looks like an np array 
narray = np.array([1,2,3,4]) # Define a numoy array 



Note the diffrence between python list and numpy array 

In [5]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


# Algebric operators on Numpy arrays vs. Python list 

In [6]:
print(narray+narray)
print(alist + alist )

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [8]:
print(narray * 3)
print(alist * 3 )

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# Matrix or Array of Arrays

In linear algebra, a matrix is a structured compoosed of n rows by m columns. That means each row must have the same number of columns. With Numpy, we have two ways to create a matrix. 

creating an array of of arrays using np.array(recomendded)
creating a matrix using np.matrix (still available but might be removed soon)


NumPy arrays or list can be used to initalizea matrix, but the resulting matrix will be composed of numpy arrays only. 


In [9]:
npmatrix1 = np.array([narray,narray,narray]) # matrix intialized with numpy arrays
npmatrix2 = np.array([alist, alist, alist ]) #matrix initialised with lists
npmatrix3 = np.array([narray, [1,1,1,1], narray]) # matrix initialized with both types 

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


Analyze the following two examples:


In [10]:
# Example 1:
okmatrix = np.array([[1,2],[3,4]]) # define a 2x2 matrix
print(okmatrix) # print matirx
print(okmatrix*2) # print a scaled version of okmatrix

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [12]:
# Example 2 

badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]]) # Define a matrix. Note the third row contains 3 elements 
print(badmatrix) # print the malformed matrix
print(badmatrix * 2) # it is supposed to scale the whole matrix

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# Scalign and translating matrices 

Now that you know how to build correct numpy arrays and matrices, let us see how easy it is to operate with them in Python using the regular algebric operators like + and - . 

Operations can be performed between arrays and arrays or between arrays and scalars

In [14]:
# Scale by 2 and translate 1 unit the matrix 
result = okmatrix * 2 + 1
print(result )

[[3 5]
 [7 9]]


In [17]:
# add two compatible matrix 

result = okmatrix + okmatrix 
print(result )

# subtract two matrix 
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [19]:
# the product * operator * when used on arrays or matrices indicates element wise multiplications. DO not confuse it with the dot product 
result = okmatrix * okmatrix 
print(result )

[[ 1  4]
 [ 9 16]]
